# Generated by Django 6.0 on 2025-12-28 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('ai_score', models.FloatField(blank=True, help_text='امتیاز از 0 تا 100', null=True, verbose_name='امتیاز هوش مصنوعی')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='بازخورد هوش مصنوعی')),
                ('similar_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ایده\u200cهای مشابه')),
                ('visibility', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='public', max_length=10, verbose_name='وضعیت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='ideas.category', verbose_name='دسته\u200cبندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ایده',
                'verbose_name_plural': 'ایده\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='تگ')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ideas.idea')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
            },
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['-created_at'], name='ideas_idea_created_f8487a_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['user', '-created_at'], name='ideas_idea_user_id_63052b_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['visibility'], name='ideas_idea_visibil_63c967_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ideatag',
            unique_together={('idea', 'name')},
        ),
    ]
