# Generated by Django 6.0 on 2025-12-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد ویرایش'),
        ),
        migrations.AddField(
            model_name='idea',
            name='scoring_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد امتیازگیری'),
        ),
    ]
