# Generated by Django 6.0 on 2025-12-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_edit_count_idea_scoring_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='last_scored_description',
            field=models.TextField(blank=True, verbose_name='توضیحات در زمان آخرین امتیازدهی'),
        ),
    ]
