# Generated by Django 6.0 on 2025-12-28 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_last_scored_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='budget',
            field=models.CharField(blank=True, help_text='مثال: ۵۰ تا ۱۰۰ میلیون تومان', max_length=100, verbose_name='بودجه تقریبی'),
        ),
        migrations.AddField(
            model_name='idea',
            name='execution_steps',
            field=models.TextField(blank=True, help_text='توضیح مراحل پیاده\u200cسازی ایده', verbose_name='مراحل اجرا'),
        ),
        migrations.AddField(
            model_name='idea',
            name='required_skills',
            field=models.TextField(blank=True, help_text='تخصص\u200cها و مهارت\u200cهای لازم برای اجرا', verbose_name='تخصص\u200cهای مورد نیاز'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='ideas.idea', verbose_name='ایده')),
            ],
            options={
                'verbose_name': 'جلسه چت',
                'verbose_name_plural': 'جلسات چت',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'مشاور AI'), ('system', 'سیستم')], max_length=20, verbose_name='نقش')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('suggested_action', models.JSONField(blank=True, help_text='JSON containing action type and data', null=True, verbose_name='اکشن پیشنهادی')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ideas.chatsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'پیام چت',
                'verbose_name_plural': 'پیام\u200cهای چت',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فیلد')),
                ('field_type', models.CharField(choices=[('text', 'متنی'), ('textarea', 'متن بلند'), ('checkbox', 'چک\u200cباکس'), ('checklist', 'چک\u200cلیست'), ('select', 'انتخابی'), ('number', 'عددی')], default='text', max_length=20, verbose_name='نوع فیلد')),
                ('value', models.TextField(blank=True, help_text='برای چک\u200cلیست و انتخابی از JSON استفاده کنید', verbose_name='مقدار')),
                ('options', models.TextField(blank=True, help_text='برای فیلد انتخابی - JSON array', verbose_name='گزینه\u200cها')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='ideas.idea', verbose_name='ایده')),
            ],
            options={
                'verbose_name': 'فیلد سفارشی',
                'verbose_name_plural': 'فیلدهای سفارشی',
                'ordering': ['order', 'id'],
            },
        ),
    ]
