# Generated by Django 6.0 on 2025-12-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_idea_budget_idea_execution_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='blocks',
            field=models.JSONField(blank=True, default=list, help_text='\n        JSON array of blocks. Each block has:\n        - type: checklist | tags | progress | link | node_graph\n        - name: string (display name)\n        - value: varies by type\n          - checklist: [{text, done}, ...]\n          - tags: [{text, color}, ...]\n          - progress: number (0-100)\n          - link: [{url, title}, ...]\n          - node_graph: {nodes: [{id, type, label, x, y, color}], edges: [{from, to}]}\n        ', verbose_name='بلوک\u200cهای پیشرفته'),
        ),
    ]
