# Generated by Django 6.0 on 2025-12-29 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_add_blocks_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('is_edited', models.BooleanField(default=False, verbose_name='ویرایش شده')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ideas.idea', verbose_name='ایده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ideas.comment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('confirmed', 'تایید شده (تکراری)'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('ai_similarity_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد شباهت AI')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='تحلیل AI')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('original_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_for_reports', to='ideas.idea', verbose_name='ایده اصلی')),
                ('reported_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_reports', to='ideas.idea', verbose_name='ایده گزارش\u200cشده')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
            ],
            options={
                'verbose_name': 'گزارش تکراری',
                'verbose_name_plural': 'گزارش\u200cهای تکراری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('investment', 'سرمایه\u200cگذاری شراکتی'), ('purchase', 'خرید کامل')], max_length=20, verbose_name='نوع درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('negotiation', 'در حال مذاکره'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('amount', models.CharField(blank=True, max_length=100, verbose_name='مبلغ پیشنهادی')),
                ('share_percentage', models.PositiveIntegerField(blank=True, help_text='برای سرمایه\u200cگذاری شراکتی', null=True, verbose_name='درصد شراکت')),
                ('message', models.TextField(blank=True, help_text='توضیحات اولیه سرمایه\u200cگذار', verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_requests', to='ideas.idea', verbose_name='ایده')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='سرمایه\u200cگذار')),
            ],
            options={
                'verbose_name': 'درخواست سرمایه\u200cگذاری',
                'verbose_name_plural': 'درخواست\u200cهای سرمایه\u200cگذاری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ideas.investmentrequest', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'پیام مذاکره',
                'verbose_name_plural': 'پیام\u200cهای مذاکره',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='ideas.idea', verbose_name='ایده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_ideas', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ستاره',
                'verbose_name_plural': 'ستاره\u200cها',
                'unique_together': {('idea', 'user')},
            },
        ),
    ]
