# Generated by Django 6.0 on 2025-12-28 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('idea_created', 'ایده جدید ثبت شد'), ('idea_deleted', 'ایده حذف شد'), ('ai_scored', 'امتیاز AI دریافت شد'), ('bonus', 'امتیاز اضافی')], max_length=20, verbose_name='عملیات')),
                ('points_change', models.IntegerField(verbose_name='تغییر امتیاز')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ امتیاز',
                'verbose_name_plural': 'لاگ\u200cهای امتیاز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='امتیاز کل')),
                ('ideas_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ایده\u200cها')),
                ('avg_ai_score', models.FloatField(default=0, verbose_name='میانگین امتیاز AI')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز کاربر',
                'verbose_name_plural': 'امتیازات کاربران',
                'ordering': ['-total_score'],
                'indexes': [models.Index(fields=['-total_score'], name='scoring_use_total_s_f79aad_idx'), models.Index(fields=['rank'], name='scoring_use_rank_a6a07a_idx')],
            },
        ),
    ]
