# Generated by Django 6.0 on 2025-12-29 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscore',
            options={'ordering': ['-sum_ai_score'], 'verbose_name': 'امتیاز کاربر', 'verbose_name_plural': 'امتیازات کاربران'},
        ),
        migrations.RemoveIndex(
            model_name='userscore',
            name='scoring_use_total_s_f79aad_idx',
        ),
        migrations.AddField(
            model_name='userscore',
            name='sum_ai_score',
            field=models.PositiveIntegerField(default=0, verbose_name='مجموع امتیاز AI'),
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['-sum_ai_score'], name='scoring_use_sum_ai__58498e_idx'),
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['-avg_ai_score'], name='scoring_use_avg_ai__9efd89_idx'),
        ),
    ]
