# Generated by Django 6.0 on 2025-12-28 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام پلن')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان/ماه)')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
                ('ideas_per_day', models.PositiveIntegerField(default=3, verbose_name='تعداد ایده در روز')),
                ('ai_chats_per_day', models.PositiveIntegerField(default=5, verbose_name='تعداد پیام چت AI در روز')),
                ('ai_scoring_attempts', models.PositiveIntegerField(default=3, verbose_name='دفعات امتیازگیری هر ایده')),
                ('custom_fields_per_idea', models.PositiveIntegerField(default=3, verbose_name='تعداد فیلد سفارشی هر ایده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='subscriptions.subscriptionplan', verbose_name='پلن')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک کاربر',
                'verbose_name_plural': 'اشتراک\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('idea_create', 'ثبت ایده'), ('ai_chat', 'چت با AI'), ('ai_score', 'امتیازگیری AI')], max_length=20, verbose_name='نوع مصرف')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ مصرف',
                'verbose_name_plural': 'لاگ\u200cهای مصرف',
                'indexes': [models.Index(fields=['user', 'date'], name='subscriptio_user_id_67d9c7_idx')],
                'unique_together': {('user', 'usage_type', 'date')},
            },
        ),
    ]
